site_name: Sendanor
site_url: https://sendanor.com/
site_author: Sendanor
remote_branch: master
docs_dir: src
site_dir: docs
copyright: Copyright (c) 2007-2021. <a href="mailto:info@sendanor.com">Sendanor</a>. All rights reserved.
nav:
- Home: 'index.md'
- Roadmap: 'roadmap.md'
- Documentation:
  - 'Forms':
      - 'Getting Started': 'forms/index.md'
      - 'Examples': 'forms/examples/commenting-on-blog.md'
  - 'Pipelines':
      - 'Getting Started': 'pipelines/index.md'
      - 'Pipeline Agents': 'pipelines/agent/index.md'
      - 'Pipeline Runner': 'pipelines/runner/index.md'
  - 'Chat':
    - 'Getting Started': 'chat/index.md'
  - 'Live':
    - 'Getting Started': 'live/index.md'
theme:
  favicon: img/favicon.ico
  logo: assets/sendanor.svg
  name: material
  locale: en
  highlightjs: true
  features:
  - header.autohide
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.top
  - toc.integrate
plugins:
- search:
    min_search_length: 2
    indexing: 'full'
extra_css:
- stylesheets/extra.css
markdown_extensions:
- attr_list
- pymdownx.tabbed
- pymdownx.superfences
- toc:
    permalink: true
extra:
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/sendanor
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sendanor/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sendanorcom
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dVTpkTh
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/sendanor/
